### PR TITLE
Update API

### PR DESCRIPTION
**Pull request by youben11**
Since both encryption schemes uses different set of parameters and might output different keys, I guess we can have the generation return an object (lets call it a store, I just didn't find a good name) that holds the different schemes information and keys that can be passed later to encryption, decryption and other related functions. Those functions (such as encrypt) should use the store's attributes (such as the public key) to encrypt the values passed.

### CODE REVIEW

**Comment by youben11** [comment]
I'm not advocating the `generateKeyStore` function name here, you can consider them as placeholder and come up with a more significant name.

**Comment by kevmo314** [comment]
Would it make sense to make `encrypt`, `decrypt`, `add`, and `multiply` instance methods on the key store? Because presumably eg encrypting with the private key won't be particularly useful.

**Comment by cereallarceny** [comment]
I like what @kevmo314 was saying, perhaps this instead @youben11 :

```js
import psi from 'psi.js/paillier';
// For SEAL, instead of Paillier: import psi from 'psi.js/seal';

const keyStore = await psi.generateKeyStore(params);

let a = keyStore.encrypt(3);
let b = keyStore.encrypt(7);

let encryptedSum = keyStore.add(a, b);
let sum = keyStore.decrypt(encryptedSum); // 10

let encryptedProduct = keyStore.multiply(a, 6);
let product = keyStore.decrypt(encryptedSum); // 18
```

**Comment by youben11** [comment]
@cereallarceny @kevmo314 This looks really convenient, however, we still should find a meaningful name to the generator function as well as the object that will hold the parameters and do all the ops.

**Comment by kevmo314** [comment]
We could cop out and let the user define it perhaps? There's no need for a separate namespace if we're just exporting a single function `f(params) -> { encrypt, decrypt, add, multiply }`.

```
import wooPsiNameHere from 'psi.js/paillier';
// For SEAL, instead of Paillier: import psi from 'psi.js/seal';

const keyStore = await wooPsiNameHere(params);

let a = keyStore.encrypt(3);
let b = keyStore.encrypt(7);

let encryptedSum = keyStore.add(a, b);
let sum = keyStore.decrypt(encryptedSum); // 10

let encryptedProduct = keyStore.multiply(a, 6);
let product = keyStore.decrypt(encryptedSum); // 18
```

**Comment by cereallarceny** [comment]
Oh that's sexy @kevmo314. Love that. Although your `await` call needs an `async` function to wrap.

One question I'd have relating to that API is how transferable it would be to other languages. Do Python, Kotlin, or Swift have the ability to do something similar? Perhaps async/await and Promises would not be required if the code were blocking. I'm not sure I know enough about those other languages to confirm they'd support such an API.

Can anyone confirm if that'd work?

**Comment by youben11** [comment]
@kevmo314 the thing is that those schemes will need to generate and keep track of some states (parameters, keys and so on), and returning stateless functions isn't the best way to go, also, if those are objects, then I guess we would have replications of some values across them.

**Comment by kevmo314** [comment]
The functions don't have to be stateless, it's just allowing the user to destructure if they prefer. The values (keys, etc) can be shared across the corresponding functions.

**Comment by iamtrask** [comment]
We could probably make these a bit higher level - i.e. expose these but also offer a higher level API for sets between different types of objets (such as GPS coordinates encoded as 1-hot vectors)

**Comment by jopasserat** [comment]
> @cereallarceny @kevmo314 This looks really convenient, however, we still should find a meaningful name to **the generator function as well as the object that will hold the parameters** and do all the ops.

I think the notion you're after @youben11 is a `context` object.
That's also the term chosen in the HE standard API description (worth skimming through it quickly :) ) 

http://homomorphicencryption.org/white_papers/API_homomorphic_encryption_white_paper.pdf

In particular, the sections "_Cryptographic Context_" and "_Payload Representation_" are highly relevant for the PSI effort.

My 2p.

**Comment by s0l0ist** [comment]
@jopasserat, yes this is definitely what we need, a `context` even SEAL has this already baked in.

I would caution the use of classes in JS as the new keyword often breaks a modular code-base. Everything should be done with function composition here. Ultimately, these implementations are not really compatible and it's always going to be a mess. The user will have to keep in mind of his chosen context and not rely on the library to solve every problem.

If you want batteries included, each implementation will need to keep track of its own state. Paillier is less so dependent on this as opposed to SEAL which has a lot of state to manage.

Example module interface needs to implement several methods:
```javascript
init, // contains the encryption parameters used for the context, sets up initial state, keygen, etc.
encode, // Paillier wouldn't need these
decode,
encrypt, 
decrypt,
evaluate, // Contains all HE evaluation methods: ex `add`, `addPlain`, `multiply`, `multiplyPlain`, etc. 
```

Which turns into something like this in application use:
```javascript
// export a default name so the user can choose the name
import { default as crypto } from 'psi.js' // Could separate the namespace as well like psi.js/paillier.

/// ******** PAILLIER ***********
const { init, encrypt, decrypt } = crypto.pailler

await init({ keySize: 1024, ...}) // Initialize with parameters, and optional existing keys

const cipher = await encrypt(5) // Only supports integers

// should have instance properties to serialize/deserialize on both types of variables (cipher, plain)
const savedCipher = cipher.save() // returns some serialized object, string, array, etc.
const loadedCipher = cipher.load(savedCipher) // overwrites internal instance.
const result = await decrypt(cipher)

/// ******** SEAL ***********
const { init, encode, decode, } = crypto.seal

await init({ polyModulusDegree: 4096, ...})

// Because SEAL depends on typed arrays, we compose our set of functions we will use for the app use-case.
const decodeInt32= array => decode(array, true) // Type of decode depends on encryption parameters (BFV supports two different typed arrays vs CKKS)

// Or if we wanted Uint32Arrays
// const decodeUint32= array => crypto.seal.decode(array, false)

// Utility
const pipe = (...functions) => x => functions.reduce((y, f) => f(y), x)

// Finally, our desired functions
const myEncrypt = pipe(encode, encrypt)
const myDecrypt = pipe(decrypt, decodeInt32)

const cipher = await myEncrypt(Int32Array.from([5]))
const result = await myDecrypt(cipher)


```

**Comment by kevmo314** [comment]
@s0l0ist re:

```
await init({ keySize: 1024, ...}) // Initialize with parameters, and optional existing keys

const cipher = await encrypt(5) // Only supports integers
```

This approach would mandate a single global state, which would prohibit the use of multiple parameterizations, if desired. We can avoid the usage of new by just creating a functional closure:

```
const { encrypt, decrypt } = await crypto.paillier({ keySize: 1024, ...}) // Initialize with parameters, and optional existing keys

const cipher = await encrypt(5) // Only supports integers
```

**Comment by s0l0ist** [comment]
Yes, that could also definitely work.

**Comment by youben11** [comment]
We took a different approach

**Pull request closed without merging**
